### PR TITLE
Update SSL certificate to use 2020

### PR DESCRIPTION
**Pull request by sbesson**
Unsure whether this can be deployed remotely or it needs to be executed from the master node

### CODE REVIEW

**Comment by joshmoore** [comment]
Where could this be documented so that the next person doing the migration will be able to find it? Could the value be a variable from `management_tools`?

**Comment by manics** [comment]
It should be deployable from anywhere inside SLS, using the kubeconfig `pass show ops/k8s/ome-lochy/admin.conf`

**Review by manics — APPROVED** [review]
Happy to deploy together over zoom tomorrow if you want.

**Comment by manics** [comment]
An alternative is to use a fixed name (without a date), and just replace the secret with the updated certificate. Doesn't help remind us to do it though.

**Comment by joshmoore** [comment]
> Doesn't help remind us to do it though.

Yeah, and that's the bit I find more concerning. Alternatively a README somewhere that is clearly linked from some place that one would _definitely_ update.

**Pull request merged**
